### ISSUE TITLE
Add ability to set the internal encoding format

### ISSUE THREAD

**Issue by rick-nu** [particle-php/Filter#11]
Add the ability to change the encoding standard. PHP uses `mb_` functions to do that (for example: md_strtolower).

```
$f = new Filter;

$f->setEncoding('UTF-16');

$f->value('first_name')->trim();
```

**Comment by berry-langerak** [comment]
Actually, I'm pretty sure it's `mb_` (multi byte).

**Comment by rick-nu** [comment]
Feature solved in https://github.com/particle-php/Filter/pull/28 as good as possible.
